[theme]

# Base colors can be 'light' or 'dark'
base = "light"

# Primary color for your app, specified as a hex or named CSS color
primaryColor = "#43718b"

# Background color for your app
backgroundColor = "#dac6d7"

# Secondary background color for your app
secondaryBackgroundColor = "#e8dae6"

# Text color for your app
textColor = "#3c455c"

# Font for your app, choose between "sans serif", "serif", and "monospace"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false

[server]
enableStaticServing = false

[upload]
file_formats = ["csv", "xlsx"]
