[theme]

# Base colors can be 'light' or 'dark'
base = "light"

# Primary color for your app, specified as a hex or named CSS color
primaryColor = "#e48038"

# Background color for your app
backgroundColor = "#FFFFFF"

# Secondary background color for your app
secondaryBackgroundColor = "#FFFFFF"

# Text color for your app
textColor = "#262730"

# Font for your app, choose between "sans serif", "serif", and "monospace"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false

[server]
enableStaticServing = false

[upload]
file_formats = ["csv", "xlsx"]
